apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-logs-pv
  labels:
    {{- include "dataapi.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: /mnt/data/logs