apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-logs-pvc
  labels:
    {{- include "dataapi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}