#=============================== ABN APP DEFINITION =============================== #
fullnameOverride: ""
nameOverride: ""

#=============================== BACKEND API DEFINITION =============================== #
backendApi:
  image:
    repository: backend-api
    pullPolicy: Never    
    tag: "latest"  
  integrationKeySecretName: "" 
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:  
    create: true    
    annotations: {}
    name: "backend-api-service-account"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext:
    capabilities:
      drop:
      - ALL    
    runAsNonRoot: true
    runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}    
    hosts:
      - host: backend-api.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

#=============================== DATA API DEFINITION =============================== #
dataApi:
  replicaCount: 1  
  image:
    repository: data-api
    pullPolicy: Never    
    tag: "latest"  
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:  
    create: true    
    annotations: {}
    name: "data-api-service-account"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext:
    capabilities:
      drop:
      - ALL    
    runAsNonRoot: true
    runAsUser: 1001
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations: {}    
    hosts:
      - host: data-api.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

  livenessProbe:
    httpGet:
      path: /
      port: 5000
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /
      port: 5000
    timeoutSeconds: 10
    initialDelaySeconds: 5
  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard